import Head from 'next/head';

import styled from "styled-components";
import BasicLayout from '../../layout/Basic';

import { Header } from '../components/Header';

const Main = styled.main`
  background-color: yellow;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>PedidoPago | Dev Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <Header />
        <Main>
        </Main>
      </BasicLayout>
    </>
  );
};
