import Head from 'next/head';
import styled from "styled-components";
import BasicLayout from '../layout/Basic';

const Main = styled.main`
  background-color: yellow;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>PedidoPago | Dev Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <Main>
          <h1>Hello World!</h1>
        </Main>
      </BasicLayout>
    </>
  );
};
